export const ADD_OPTION = 'ADD_OPTION';
export const DELETE_OPTION = 'DELETE_OPTION';
export const LOAD_OPTIONS_SUCCESS = 'LOAD_OPTIONS_SUCCESS';
export const EMPTY_LIST = 'EMPTY_LIST';

export const ADD_LIST_SUCCESS = 'ADD_LIST_SUCCESS';
export const LOAD_LISTS_SUCCESS = 'LOAD_LISTS_SUCCESS';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';


